SEASONS = "seasons"
SUMMER = "summer"
WINTER = "winter"
START = "start"
PEAK = "peak"

ID = "id"
SPEED = "speed"
START = "start"
SUMMER_DURATION = "summer_duration"
WINTER_DURATION = "winter_duration"